name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: netology_django_testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        # Добавляем параметры для ускорения запуска
        volumes:
          - postgres_data:/var/lib/postgresql/data
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django psycopg2-binary

    - name: Wait for PostgreSQL (увеличенное время ожидания)
      run: |
        timeout 60s bash -c 'until pg_isready -h postgres -p 5432; do sleep 2; echo "Waiting for PostgreSQL..."; done'
        echo "PostgreSQL is ready!"

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:123@postgres:5432/netology_django_testing
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:123@postgres:5432/netology_django_testing
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        pytest
