name: Django CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: netology_django_testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 1s
          --health-retries 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt psycopg2-binary pytest-django

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to become ready..."
        for i in {1..30}; do
          if nc -z localhost 5432; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          sleep 2
          echo "Attempt $i/30 - PostgreSQL not ready yet"
        done
        echo "PostgreSQL connection failed"
        exit 1

    - name: Verify PostgreSQL connection
      run: |
        PGPASSWORD=123 psql -h localhost -U postgres -d netology_django_testing -c "SELECT 1" || (echo "Failed to connect to PostgreSQL"; exit 1)

    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        pytest
