name: Django CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Явно включаем поддержку Docker
    container:
      image: ubuntu:22.04
      options: --network=host

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: netology_django_testing
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 1s
          --health-retries 30
          --network=host

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python and PostgreSQL client
      run: |
        apt-get update && apt-get install -y python3 python3-pip postgresql-client
        python3 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt psycopg2-binary pytest-django

    - name: Verify PostgreSQL connection
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..30}; do
          if PGPASSWORD=123 psql -h localhost -U postgres -d netology_django_testing -c "SELECT 1" >/dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          sleep 2
          echo "Attempt $i/30 - PostgreSQL not ready yet"
        done
        echo "PostgreSQL connection failed after 30 attempts"
        exit 1

    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        pytest
