name: Django CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: netology_django_testing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 10
        # Критически важные параметры:
        volumes:
          - pgdata:/var/lib/postgresql/data
        env:
          POSTGRES_HOST_AUTH_METHOD: trust  # Отключаем парольную аутентификацию для CI

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt psycopg2-binary pytest-django

    - name: Verify PostgreSQL connection
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..10}; do
          if pg_isready -h postgres -p 5432 -U postgres -d netology_django_testing; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          sleep 3
          echo "Attempt $i/10 failed"
        done
        echo "PostgreSQL connection failed"
        exit 1

    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: django_testing.settings
      run: |
        pytest
